sudo: required

dist: trusty

branches:
  only:
    - master

language: go

go:
  - 1.12.x

env:
  - KUBECONFIG=${HOME}/.kube/config PATH=$HOME/k8scli:$HOME/tool:$HOME/google-cloud-sdk/bin:${PATH} GO111MODULE=on DOCKER_CACHE_DIR=${HOME}/docker/

cache:
  directories:
    - $HOME/google-cloud-sdk/
    - $HOME/k8scli
    - $HOME/tool
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

services:
  - docker

before_install:
  - sudo apt-get update
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - sudo apt-get -y install apache2-utils parallel realpath
  - sudo sysctl net.ipv6.conf.all.disable_ipv6=0
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart

install:
  - hack/travis-kube-setup.sh

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - go mod download
  - hack/verify-staticcheck.sh
  - hack/verify-gofmt.sh
  - hack/verify-govet.sh
  - helm lint charts/fission-all/ charts/fission-core/
  - hack/runtests.sh
  - test/build.sh

script:
  - cd ${TRAVIS_BUILD_DIR}
  - test/test.sh
  - test/upgrade/fission_upgrade_test.sh

after_script:
  - bash <(curl -s https://codecov.io/bash)
  - kubectl --namespace default delete configmap -l travisID=${TRAVIS_BUILD_ID} # remove in-test configmap to indicate this CI build finished
